### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by mslinn** [ariatemplates/git-release-notes#1]
I'm running Ubuntu 14.04. I am not a nodejs programmer, so I need to know how to launch git-release-notes once installed. I installed this way:

```
$ sudo npm install -g git-release-notes
npm http GET https://registry.npmjs.org/git-release-notes
npm http 304 https://registry.npmjs.org/git-release-notes
npm http GET https://registry.npmjs.org/ejs
npm http GET https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/ejs
npm http GET https://registry.npmjs.org/ejs/-/ejs-0.8.8.tgz
npm http 200 https://registry.npmjs.org/optimist
npm http 200 https://registry.npmjs.org/ejs/-/ejs-0.8.8.tgz
npm http GET https://registry.npmjs.org/wordwrap
npm http 200 https://registry.npmjs.org/wordwrap
/usr/bin/git-release-notes -> /usr/lib/node_modules/git-release-notes/index.js
git-release-notes@0.0.1 /usr/lib/node_modules/git-release-notes
├── ejs@0.8.8
└── optimist@0.3.7 (wordwrap@0.0.2)
```

The instructions seem to say to run from the command line this way, but this is obviously naive of me, so I kept trying: 

```
$ git-release-notes HEAD~10..HEAD
git-release-notes: command not found

$ nodejs git-release-notes HEAD~10..HEAD

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/mslinn/work/training/projects/public_code/play/course_play_scala_intro_code/git-release-notes'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
mslinn@oneiric course_play_scala_intro_code (master)

$ node git-release-notes HEAD~10..HEAD
mslinn@oneiric course_play_scala_intro_code (master)
```

**Comment by piuccio** [comment]
I think it's because you've installed it using `sudo` and then running the script as normal user.

Try `npm install -g git-release-notes`

Anyway, it's quite old, I'm closing this
