### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Hunsu** [ariatemplates/git-release-notes#10]
$ git-release-notes 8da17b57f77db9f97820de37f4a69183489faaa8..4c385414d0f98ca20f6283db5e25e2bd5f547d3b html
/usr/local/lib/node_modules/git-release-notes/lib/git.js:43
            workingCommit.messageLines.push(line.message);
                         ^

TypeError: Cannot read property 'messageLines' of undefined
    at /usr/local/lib/node_modules/git-release-notes/lib/git.js:43:17
    at Array.forEach (native)
    at processCommits (/usr/local/lib/node_modules/git-release-notes/lib/git.js:35:9)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/git-release-notes/lib/git.js:17:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

Maybe related to https://github.com/ariatemplates/git-release-notes/issues/8.

**Comment by mengzdsd** [comment]
I got the same error:
```
$git-release-notes 4cfa07d..abbbc85 markdown
/home/mengz/Dev/node-v5.1.0-linux-x64/lib/node_modules/git-release-notes/lib/git.js:43
                        workingCommit.messageLines.push(line.message);
                                     ^

TypeError: Cannot read property 'messageLines' of undefined
    at /home/mengz/Dev/node-v5.1.0-linux-x64/lib/node_modules/git-release-notes/lib/git.js:43:17
    at Array.forEach (native)
    at processCommits (/home/mengz/Dev/node-v5.1.0-linux-x64/lib/node_modules/git-release-notes/lib/git.js:35:9)
    at ChildProcess.<anonymous> (/home/mengz/Dev/node-v5.1.0-linux-x64/lib/node_modules/git-release-notes/lib/git.js:17:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by arfoll** [comment]
My guess it it's to do with more recent versions of git and the %w flag seems to have changed, I couldn't quite fix it it though so maybe something else at play
