### ISSUE TITLE
TypeError: Cannot read property 'messageLines' of undefined

### ISSUE THREAD

**Issue by avtaniket** [ariatemplates/git-release-notes#14]
First time command works properly,
`git-release-notes v1.0..v1.1 markdown`

But when running same command again throws error

```
TypeError: Cannot read property 'messageLines' of undefined
    at /home/.nvm/versions/node/v4.0.0/lib/node_modules/git-release-notes/lib/git.js:43:17
    at Array.forEach (native)
    at processCommits (/home/.nvm/versions/node/v4.0.0/lib/node_modules/git-release-notes/lib/git.js:35:9)
    at ChildProcess.<anonymous> (/home/.nvm/versions/node/v4.0.0/lib/node_modules/git-release-notes/lib/git.js:17:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
Any suggestions?

**Comment by piuccio** [comment]
do you have a public repo on which we can run the command?

**Comment by avtaniket** [comment]
Sorry, I don't have such. I was trying this for a private project.

Let me know if you need any specific information.

**Comment by piuccio** [comment]
Do you mind pasting the output of this command?

```
git log --no-merges --branches=master --format=sha1:%h v1.0..v1.1
```
